# Generated by Django 3.1.3 on 2020-11-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
